"""
@Author  : Yang-yang Miao
@Email   : yangyangmiao666@icloud.com
@Time    : 2025/11/18 00:13
@Desc    : constants.py
"""
OPENAI_API_KEY = "OPENAI_API_KEY"
OPENAI_BASE_URL = "OPENAI_BASE_URL"
OPENAI_MODEL_NAME = "OPENAI_MODEL_NAME"

REDIS_HOST = "REDIS_HOST"
REDIS_PORT = "REDIS_PORT"
REDIS_PASSWORD = "REDIS_PASSWORD"

LANGFUSE_SECRET_KEY = "LANGFUSE_SECRET_KEY"
LANGFUSE_PUBLIC_KEY = "LANGFUSE_PUBLIC_KEY"
LANGFUSE_HOST = "LANGFUSE_HOST"

LLM_NODE = "llm_node"
TOOL_NODE = "tool_node"

MCP_BASE_URL = "MCP_BASE_URL"
MCP_ENDPOINT = "MCP_ENDPOINT"

POSTGRES_USER = "POSTGRES_USER"
POSTGRES_PASSWORD = "POSTGRES_PASSWORD"
POSTGRES_HOST = "POSTGRES_HOST"
POSTGRES_PORT = "POSTGRES_PORT"
POSTGRES_DB = "POSTGRES_DB"